source 'http://rubygems.org'

gem 'sinatra', '~> 1.4.0'
gem 'sinatra-contrib'
gem 'unicorn'
gem 'pry'
gem 'pry-doc'
gem 'pry-byebug'
gem 'rubyzip'
gem 'mongoid', '~> 7.0'
gem "will_paginate_mongoid"
gem 'bcrypt'
gem 'waveinfo'
gem 'awesome_print'

gem 'rspec'
gem 'guard'
gem 'guard-rspec'
gem 'time_difference'
gem 'rubycritic'
